version: "3.9"
services:
  readme.account.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.account.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: readme-account

    ports:
      - 27017:27017

    volumes:
      - readme.mongo.account:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/readme-account --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  typeoteka.account.mongo.ui:
    image: mongo-express
    restart: always
    container_name: readme.account.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://admin:123456@readme.account.mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123456

volumes:
  readme.mongo.account:
